projects:
  app:
    schemaPath: src/graphql-server/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: src/graphql-server/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml